# Cf https://www3.ntu.edu.sg/home/ehchua/programming/howto/Cygwin_HowTo.html
name: Build DLL Hijacking library
on:
  # On demand only because only local resources are used.
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Cygwin, compilers and setup environment 
        shell: powershell
        run: .\Install-Cygwin.ps1
      - name: Compile the library for 32 and 64 bits Windows OS
        shell: powershell
        run: .\Build-Library.ps1
      - name: Upload library binaries
        uses: actions/upload-artifact@v2
        with:
          name: DLL_Hijacking_Compiled_Library
          path: library_dist/
