name: Build and deploy the toolbox image
env:
  IMAGE_NAME: "righettod/toolbox-pentest-web"
  REGISTRY: ghcr.io  
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build-and-push-image-dockerhub-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2      
      - name: Build and Publish image to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ env.IMAGE_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          buildoptions: "--compress --force-rm"
