# Tool "markdown-link-check" is used to validate the links
# See https://www.npmjs.com/package/markdown-link-check
# See https://github.com/gaurav-nelson/github-action-markdown-link-check
# For the config file:
# See https://github.com/gaurav-nelson/github-action-markdown-link-check#custom-variables
# See https://github.com/tcort/markdown-link-check#config-file-format
name: Check cheat sheet links validity
on:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Action
        uses: actions/checkout@v4
      - name: Run check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          max-depth: 10
          config-file: "./markdown-link-check_config.json"
